#!/bin/sh

set -e

case "$1" in
  configure)
    # Add acme-chief user
    if ! getent passwd acme-chief > /dev/null; then
        adduser --quiet --system --no-create-home --home /nonexistent \
            --group --gecos "acme-chief service" acme-chief || true
    fi

    chmod 750 /etc/acme-chief /var/lib/acme-chief \
              /var/lib/acme-chief/live_certs \
              /var/lib/acme-chief/http_challenges \
              /var/lib/acme-chief/dns_challenges
    chmod 700 /var/lib/acme-chief/new_certs /var/lib/acme-chief/csrs

    if ! getent group acme-chief > /dev/null; then
        echo "Error: acme-chief group does not exist" >&2
        exit 1
    fi
    chown acme-chief:acme-chief /etc/acme-chief /etc/acme-chief/accounts /var/lib/acme-chief \
                                  /var/lib/acme-chief/new_certs /var/lib/acme-chief/live_certs \
                                  /var/lib/acme-chief/http_challenges /var/lib/acme-chief/dns_challenges \
                                  /var/lib/acme-chief/csrs

    if ! getent passwd www-data > /dev/null; then
        echo "Error: www-data user does not exist" >&2
        exit 1
    fi

    adduser www-data acme-chief
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    :
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

#DEBHELPER#

exit 0
